"""Tests for the reproducible SVG figures (computed from the weight-free pipeline)."""

from __future__ import annotations

from pathlib import Path

from alleleforge.viz import FIGURES, render_all_figures
from alleleforge.viz.figures import (
    conformal_coverage_figure,
    generalization_gap_figure,
    reference_bias_data,
    reference_bias_figure,
    task_ece_figure,
)


def test_reference_bias_data_matches_acceptance_case() -> None:
    ref_only, pop_aware, cfd, ancestries = reference_bias_data()
    assert ref_only == 0  # a reference-only scan is blind to the off-target
    assert pop_aware == 1  # the population-aware scan nominates it
    assert cfd >= 0.20  # high-CFD off-target
    assert ancestries["afr"] == max(ancestries.values())  # AFR-enriched


def test_every_builder_renders_valid_svg() -> None:
    for builder in (
        reference_bias_figure,
        conformal_coverage_figure,
        task_ece_figure,
        generalization_gap_figure,
    ):
        svg = builder()
        assert svg.startswith("<svg")
        assert svg.rstrip().endswith("</svg>")


def test_figures_are_deterministic() -> None:
    # Same config + seed -> byte-identical SVG (safe to commit and diff).
    for builder in FIGURES.values():
        assert builder() == builder()


def test_conformal_figure_shows_recalibrated_above_raw() -> None:
    svg = conformal_coverage_figure()
    assert "Raw coverage" in svg and "Recalibrated coverage" in svg
    assert "target 80%" in svg  # the nominal-level reference line


def test_render_all_writes_every_figure(tmp_path: Path) -> None:
    written = render_all_figures(tmp_path)
    assert set(written) == set(FIGURES)
    for path in written.values():
        assert path.exists()
        assert path.read_text().startswith("<svg")


def test_render_all_creates_missing_dir(tmp_path: Path) -> None:
    target = tmp_path / "nested" / "figures"
    written = render_all_figures(target)
    assert all(p.parent == target for p in written.values())


def test_committed_figures_match_a_fresh_render(tmp_path: Path) -> None:
    """The SVGs under ``docs/assets/figures/`` must be a current render.

    They are embedded in the README and the preprint, so a stale one is a figure
    that shows numbers the pipeline no longer produces — to a reader who has no way
    to tell. `make figures` regenerates them and the README calls them
    "regenerated byte-for-byte", but nothing checked that claim: the figures are
    committed output of code that keeps changing, which is exactly the shape the
    published JSON Schemas drifted in (they had been stale for several releases
    before a test was added). Determinism, already tested above, is what makes this
    check meaningful rather than flaky.

    Regenerate with ``make figures``.
    """
    committed = Path(__file__).resolve().parents[2] / "docs" / "assets" / "figures"
    fresh = render_all_figures(tmp_path)

    assert {p.name for p in fresh.values()} == {p.name for p in committed.glob("*.svg")}, (
        "docs/assets/figures/ has files the renderer does not emit (or is missing "
        "some); run make figures"
    )
    stale = sorted(
        path.name
        for path in fresh.values()
        if (committed / path.name).read_bytes() != path.read_bytes()
    )
    assert not stale, f"committed figure(s) out of date: {', '.join(stale)}. Run make figures"


def test_every_figure_states_where_its_data_came_from() -> None:
    """A figure is the artifact most likely to be seen alone.

    A slide, an issue, a paper — the caveat in the report beside it does not travel
    with the image. All four committed figures plot numbers from synthetic stand-ins
    or constructed loci, and none said so; the ECE chart even draws a flag threshold
    across them, framing a fabricated number as a measurement against a real bar.
    """
    from alleleforge.viz.figures import FIGURES

    assert FIGURES, "no figures registered — the loop below would be vacuous"
    for name, build in FIGURES.items():
        svg = build()
        assert "SYNTHETIC" in svg or "CONSTRUCTED" in svg, (
            f"figure {name!r} plots fixture data without saying so"
        )


def test_the_note_tracks_the_data_rather_than_being_decoration() -> None:
    """A caveat printed unconditionally would be noise and would survive real data."""
    from alleleforge.viz.figures import _benchmark_data_note

    assert _benchmark_data_note([{"synthetic": True}, {"synthetic": True}])
    assert not _benchmark_data_note([{"synthetic": True}, {"synthetic": False}])
    assert not _benchmark_data_note([{"synthetic": False}])
    assert not _benchmark_data_note([])
