"""The benchmark data every score is computed from is committed, and generated by hand.

`scripts/make_benchmark_fixtures.py` writes the five dataset fixtures and the five frozen
splits under `src/alleleforge/benchmark/`. Its docstring makes the claim the whole harness
rests on — "fully deterministic — every value is derived from a SHA-256 of the row id, so
re-running produces byte-identical files and the committed content hashes stay stable" —
and nothing ran it. It is not in `make ci`, no CI job invokes it, and no test imports it:
of the nine scripts in this repository it was the only one with zero references anywhere
in the suite.

The same shape as the committed figures one file over, with more riding on it. A fixture
edited by hand — or a generator changed and not re-run — leaves committed data nothing can
reproduce, in a harness whose splits record a dataset content hash precisely so a frozen
split is invalidated the moment the data changes. The integrity check catches a fixture
edited *alone*; it cannot catch a fixture and its split hash edited together, and neither
could say the generator still produces them.

Run as a subprocess in a temporary tree, because the script writes to paths relative to
the working directory: the test must not be able to overwrite the committed files it is
checking.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
_SCRIPT = _ROOT / "scripts" / "make_benchmark_fixtures.py"
_BENCH = Path("src") / "alleleforge" / "benchmark"
_GENERATED = (_BENCH / "datasets" / "fixtures", _BENCH / "splits")


def _regenerate(into: Path) -> None:
    for relative in _GENERATED:
        (into / relative).mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        [sys.executable, str(_SCRIPT)],
        cwd=into,
        capture_output=True,
        text=True,
        check=False,
        env={"PATH": "/usr/bin:/bin", "PYTHONPATH": str(_ROOT / "src")},
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_the_committed_fixtures_are_what_the_generator_produces(tmp_path: Path) -> None:
    _regenerate(tmp_path)
    stale: list[str] = []
    produced = 0
    for relative in _GENERATED:
        for written in sorted((tmp_path / relative).glob("*.json")):
            produced += 1
            committed = _ROOT / relative / written.name
            if not committed.is_file():
                stale.append(f"{relative / written.name}: generated but not committed")
            elif committed.read_bytes() != written.read_bytes():
                stale.append(f"{relative / written.name}: differs from what the generator writes")
    assert produced >= 10, f"the generator wrote {produced} files; this check would be vacuous"
    assert not stale, (
        f"the committed benchmark data is not what its generator produces: {stale}. Every "
        "score, every split integrity hash and the leaderboard read these; regenerate with "
        "`python scripts/make_benchmark_fixtures.py` and commit the result."
    )


def test_every_committed_fixture_has_a_generator(tmp_path: Path) -> None:
    """The other direction: a file nothing generates is data with no provenance."""
    _regenerate(tmp_path)
    orphans: list[str] = []
    for relative in _GENERATED:
        for committed in sorted((_ROOT / relative).glob("*.json")):
            if not (tmp_path / relative / committed.name).is_file():
                orphans.append(str(relative / committed.name))
    assert not orphans, (
        f"these are committed under the benchmark package and the generator does not "
        f"write them: {orphans}"
    )


def test_the_generator_is_deterministic(tmp_path: Path) -> None:
    """Its own claim, run twice — the property the committed hashes depend on."""
    first, second = tmp_path / "a", tmp_path / "b"
    _regenerate(first)
    _regenerate(second)
    for relative in _GENERATED:
        for path in sorted((first / relative).glob("*.json")):
            other = second / relative / path.name
            assert path.read_bytes() == other.read_bytes(), f"{path.name} is not deterministic"
