#!/usr/bin/env python
"""Calibration study: regenerate the CRISPR-Bench calibration report (R5).

Two regenerable, deterministic-from-seed outputs:

1. **Per-task calibration table** — every CRISPR-Bench task's primary metric and
   its **ECE** (the honesty metric required on every task), measured against the
   reference baseline on the frozen splits.
2. **Conformal interval-recalibration demonstration** — on a deliberately
   miscalibrated regression set, the empirical interval coverage *before* and
   *after* :class:`~alleleforge.scoring.uncertainty.ConformalCalibrator` at the
   spec's interval levels, showing the split-conformal guarantee restore coverage
   to its nominal target.

On real weights (R1) the per-task numbers become the published reproduction; the
machinery and the report regenerate identically here on the weight-free splits.

Usage:
    python scripts/calibration_study.py            # print the markdown report
    python scripts/calibration_study.py --out PATH  # also write it to PATH
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

# The deterministic computations live in the library so the markdown report (here)
# and the SVG figures (alleleforge.viz) share one source of truth.
from alleleforge.benchmark.calibration import (
    LEVELS,
    conformal_demo,
    generalization_table,
    task_calibration_table,
)
from alleleforge.benchmark.tasks import TASKS
from alleleforge.config import get_settings

__all__ = [
    "LEVELS",
    "TASKS",
    "conformal_demo",
    "generalization_table",
    "main",
    "render_markdown",
    "task_calibration_table",
]


def render_markdown(
    tasks: list[dict[str, Any]], generalization: list[dict[str, Any]], demo: list[dict[str, Any]]
) -> str:
    """Render the calibration report as markdown."""
    lines = [
        "# CRISPR-Bench calibration report",
        "",
        "Regenerated by `scripts/calibration_study.py` from config + seed.",
        "",
        "## Per-task calibration (baseline, frozen splits)",
        "",
        "| Task | Kind | Primary | Value | ECE |",
        "|---|---|---|---:|---:|",
    ]
    for r in tasks:
        lines.append(
            f"| {r['task']} | {r['kind']} | {r['primary_metric']} | "
            f"{r['primary_value']} | {r['ece']} |"
        )
    lines += [
        "",
        "## Cross-cell-type generalization gap",
        "",
        "Primary metric on an in-context fold (a training-seen cell type) vs the",
        "held-out cell type. A positive gap means the model generalizes *worse* to",
        "the unseen context — a field-wide reality, reported, not hidden.",
        "",
        "| Task | Metric | In-context | Held-out | Gap | Held-out context |",
        "|---|---|---:|---:|---:|---|",
    ]
    for r in generalization:
        lines.append(
            f"| {r['task']} | {r['metric']} | {r['in_context']} | "
            f"{r['held_out']} | {r['gap']:+} | {r['held_out_context']} |"
        )
    lines += [
        "",
        "## Conformal interval recalibration",
        "",
        "Empirical coverage of a deliberately under-covering interval set, before and",
        "after split-conformal recalibration (synthetic, seeded). Recalibrated coverage",
        "meets the nominal level — the finite-sample guarantee.",
        "",
        "| Target level | Raw coverage | Recalibrated coverage | Width scale |",
        "|---:|---:|---:|---:|",
    ]
    for r in demo:
        lines.append(
            f"| {r['level']:.2f} | {r['raw_coverage']} | "
            f"{r['recalibrated_coverage']} | {r['scale']} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    """Regenerate and print (optionally write) the calibration report."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=None, help="also write the report to this path")
    args = parser.parse_args(argv)

    report = render_markdown(
        task_calibration_table(), generalization_table(), conformal_demo(get_settings().rng())
    )
    if args.out is not None:
        args.out.write_text(report)
        print(f"wrote {args.out}")
    print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
