#!/usr/bin/env python3
"""Generate the round index from the round log.

`openspec/changes/README.md` is this project's primary knowledge artifact and it is a
megabyte of narrative: four hundred and fifty-odd rounds, each a story with its evidence.
That shape is right for writing a round and useless for finding one. A reader who wants
"has anyone looked at cache integrity" or "what did we decide about degenerate metrics"
has no way in short of a full-text search over prose that quotes its own historical
mistakes.

This writes `ROUNDS.md`: one row per round, its title, and the first sentence of its
**Lesson**, which is the line each round is written to leave behind. It is *generated* —
a hand-maintained index of a log that grows every round is a list that goes stale by
construction, which this project has now caught in four separate guards — and
`test_the_round_index_matches_the_log` regenerates it and compares.

Usage::

    python scripts/round_index.py            # write the index
    python scripts/round_index.py --check    # exit 1 if it is out of date
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
LOG = _ROOT / "openspec" / "changes" / "README.md"
INDEX = _ROOT / "openspec" / "changes" / "ROUNDS.md"

#: A round begins at a `## Round <n> — <title>` heading.
_ROUND = re.compile(r"^## Round (\d+)\s*[—-]?\s*(.*)$", re.M)

#: The bolded lesson each round closes with. Not every early round has one.
_LESSON = re.compile(r"\*\*Lesson:?(.*?)\*\*", re.S)

#: How much of the lesson the index carries. It is a pointer, not a replacement — the
#: round itself is where the evidence lives.
_LESSON_CHARS = 160


def _first_sentence(text: str) -> str:
    """Return the lesson's opening sentence, collapsed and bounded."""
    collapsed = " ".join(text.split())
    match = re.match(r"(.+?[.?!])(?:\s|$)", collapsed)
    sentence = match.group(1) if match else collapsed
    if len(sentence) > _LESSON_CHARS:
        sentence = sentence[: _LESSON_CHARS - 1].rstrip() + "…"
    return sentence


def _cell(text: str) -> str:
    """Escape a value for a Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def rounds(log: str) -> list[tuple[int, str, str]]:
    """Return ``(number, title, lesson)`` per round, in the order the log tells them."""
    matches = list(_ROUND.finditer(log))
    out: list[tuple[int, str, str]] = []
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(log)
        body = log[match.end() : end]
        lesson = _LESSON.search(body)
        out.append(
            (
                int(match.group(1)),
                match.group(2).strip(),
                _first_sentence(lesson.group(1)) if lesson else "",
            )
        )
    return out


def render(entries: list[tuple[int, str, str]]) -> str:
    """Render the index."""
    lines = [
        "# Round index",
        "",
        "One row per round of [`README.md`](README.md), with the first sentence of the",
        "**Lesson** that round was written to leave behind. A truncated quote, not a",
        "summary: the round itself carries the evidence, the measurements and what was",
        "ruled out.",
        "",
        "Generated by `python scripts/round_index.py`; "
        "`test_the_round_index_matches_the_log` keeps it honest. Do not edit by hand.",
        "",
        f"{len(entries)} rounds. An em dash means the round predates the habit of "
        "closing with a lesson.",
        "",
        "| Round | What it was about | Lesson |",
        "| ---: | :--- | :--- |",
    ]
    for number, title, lesson in entries:
        lines.append(f"| {number} | {_cell(title)} | {_cell(lesson) or '—'} |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    """Write (or check) the index; return a process exit code."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if out of date")
    args = parser.parse_args(argv)

    rendered = render(rounds(LOG.read_text(encoding="utf-8")))
    if args.check:
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        if current != rendered:
            print(f"{INDEX} is out of date; run python scripts/round_index.py", file=sys.stderr)
            return 1
        return 0
    INDEX.write_text(rendered, encoding="utf-8")
    print(f"wrote {INDEX} ({len(rounds(LOG.read_text(encoding='utf-8')))} rounds)")
    return 0


if __name__ == "__main__":  # pragma: no cover - script entry point
    raise SystemExit(main())
